# Generated by Django 3.2.3 on 2021-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cooking_steps',
            field=models.TextField(default='Steps', max_length=4000, verbose_name='Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='CookingSteps',
        ),
    ]
