# Generated by Django 3.2.3 on 2021-06-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, default=recipes.models.get_default_recipe_image, upload_to=recipes.models.get_recipe_image_filepath)),
                ('prep_time_hh', models.SmallIntegerField()),
                ('prep_time_mm', models.SmallIntegerField()),
                ('cooking_time_hh', models.SmallIntegerField()),
                ('cooking_time_mm', models.SmallIntegerField()),
                ('ingredients', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.category')),
            ],
        ),
    ]
